### ISSUE TITLE
Create Website

### ISSUE THREAD

**Issue by Wuncemoor** [Wuncemoor/Wuncemoor#21]
- [ ] Create static HTML/CSS
- [ ]  Put it on the internet
- [ ] Add login/authentication
- [ ] Enable Devlog posting
- [ ] Enable Tagging of posts based on content
- [ ] Add navbar
- [ ] Add devlog archives
- [ ] Link to social media for 2-way exchange
- [ ] Allow readers to submit messages to admin (general and post specific)

Bonus:

- [ ] Use Django during this
- [ ]  Make additional websites for personal blog and business projects
