### ISSUE TITLE
Create Patreon

### ISSUE THREAD

**Issue by Wuncemoor** [Wuncemoor/Wuncemoor#23]
- [ ] Finish setting up the basics
- [ ] Integrate Payment
- [ ] Figure out tiers and value offering
- [ ] Integrate with other networking
